version: '3.7'

services:
  mysql:
    container_name: biblioteca-mysql
    image: biblioteca-mysql
    build:
      context: .
      dockerfile: ./dockerfile.db
    command: --default-authentication-plugin=mysql_native_password
      --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: bibliotecadb
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_HOST: '%'
    networks:
      - api-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: biblioteca-app
    image: biblioteca-app
    build:
      context: .
      dockerfile: ./Dockerfile.app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - api-network
  react:
    container_name: react
    image: biblioteca-react
    build:
      context: ./biblioteca-react/
      dockerfile: ./dockerfile.rct
    ports:
      - 3006:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - api-network
networks:
  api-network: null
